// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using ServiceMetadata within kubernetes types, where deepcopy-gen is used.
func (in *ServiceMetadata) DeepCopyInto(out *ServiceMetadata) {
	p := proto.Clone(in).(*ServiceMetadata)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMetadata. Required by controller-gen.
func (in *ServiceMetadata) DeepCopy() *ServiceMetadata {
	if in == nil {
		return nil
	}
	out := new(ServiceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMetadata. Required by controller-gen.
func (in *ServiceMetadata) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
