// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for PublishServiceMetadataRequest
func (this *PublishServiceMetadataRequest) MarshalJSON() ([]byte, error) {
	str, err := ServiceMetadataMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PublishServiceMetadataRequest
func (this *PublishServiceMetadataRequest) UnmarshalJSON(b []byte) error {
	return ServiceMetadataUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PublishServiceMetadataResponse
func (this *PublishServiceMetadataResponse) MarshalJSON() ([]byte, error) {
	str, err := ServiceMetadataMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PublishServiceMetadataResponse
func (this *PublishServiceMetadataResponse) UnmarshalJSON(b []byte) error {
	return ServiceMetadataUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GetServiceMetadataRequest
func (this *GetServiceMetadataRequest) MarshalJSON() ([]byte, error) {
	str, err := ServiceMetadataMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GetServiceMetadataRequest
func (this *GetServiceMetadataRequest) UnmarshalJSON(b []byte) error {
	return ServiceMetadataUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GetServiceMetadataResponse
func (this *GetServiceMetadataResponse) MarshalJSON() ([]byte, error) {
	str, err := ServiceMetadataMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GetServiceMetadataResponse
func (this *GetServiceMetadataResponse) UnmarshalJSON(b []byte) error {
	return ServiceMetadataUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ServiceMetadataMarshaler   = &jsonpb.Marshaler{}
	ServiceMetadataUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
